name: Test
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  push:
    branches: [main]

jobs:
  linux-tests:
    strategy:
      matrix:
        swift: ["6.3", "6.2", "6.1", "6.0"]
    name: Test for Swift ${{ matrix.swift }} on Ubuntu
    runs-on: ubuntu-24.04
    container: swift:${{ matrix.swift }}-bookworm
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
    - uses: swift-actions/setup-swift@7ca6abe6b3b0e8b5421b88be48feee39cbf52c6a # v2.4.0
      with:
        swift-version: ${{ matrix.swift }}
    - name: Install xcbeautify
      if: startsWith(matrix.os, 'ubuntu-')
      run: brew install xcbeautify
    - name: Run tests
      run: swift test 2>&1 | xcbeautify

  macos-tests:
    strategy:
      fail-fast: false
      matrix:
        include:
        - os: macos-26
          xcode: "26.6"
          swift: "6.3"
        - os: macos-26
          xcode: "26.3"
          swift: "6.2"
        - os: macos-15
          xcode: "16.4"
          swift: "6.1"
        - os: macos-15
          xcode: "16.2"
          swift: "6.0"
    name: Test for Swift ${{ matrix.swift }} on ${{ matrix.os }} (Xcode ${{ matrix.xcode }})
    runs-on: ${{ matrix.os }}

    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
    - name: Run tests
      run: swift test | xcbeautify
